version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  tests:
    working_directory: ~/circle
    docker:
      - image: cimg/ruby:3.1.3
    steps:
      - checkout
      - setup_remote_docker
  build_and_push_image:
    working_directory: ~/circle/git/fb-adapter-template
    docker: &ecr_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key:  $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "10:76:81:db:22:4d:03:9a:33:e8:3b:64:a7:34:0c:e2"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_107681db224d039a33e83b64a7340ce2" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: master
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  deploy_to_test:
    working_directory: ~/circle/git/fb-adapter-template
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "10:76:81:db:22:4d:03:9a:33:e8:3b:64:a7:34:0c:e2"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_107681db224d039a33e83b64a7340ce2" >> $BASH_ENV
      - run: *deploy_scripts
      - run:
          name: deploy to test environment in new cluster
          environment:
            APPLICATION_NAME: fb-adapter-template
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-base-adapter-test
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status

workflows:
  version: 2
  release:
    jobs:
      - build_and_push_image:
          filters:
            branches:
              only:
                - main
                - circleci-project-setup
      - deploy_to_test:
          requires:
            - build_and_push_image
